setClass(Class = "ControlOptions", 
         slots = list(TITLEONE = "character",
                      TITLETWO = "character",
                      MODELOPT = "list",
                      AVERTIME = "list",
                      URBANOPT = "list",
                      POLLUTID = "character",
                      HALFLIFE = "numeric",
                      DCAYCOEF = "numeric",
                      FLAGPOLE = "numeric",
                      EVENTFIL = "list",
                      SAVEFILE = "list",
                      INITFILE = "character",
                      MULTYEAR = "list",
                      DEBUGOPT = "list",
                      ERRORFIL = "character",
                      RUNORNOT = "logical"),
         prototype = list(TITLEONE = "AERMODr Run",
                          TITLETWO = NULL,
                          MODELOPT = list("DFAULT"),
                          AVERTIME = list( "24"),
                          URBANOPT = NULL,
                          POLLUTID = NULL,
                          HALFLIFE = NULL,
                          DCAYCOEF = NULL,
                          FLAGPOLE = NULL,
                          EVENTFIL = list(),
                          SAVEFILE = list(),
                          INITFILE = NULL,
                          MULTYEAR = list(),
                          DEBUGOPT = list(),
                          ERRORFIL = NULL,
                          RUNORNOT = TRUE)
         
)